# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ave_gain', models.FloatField()),
                ('ave_loss', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
