# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20171120_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsimodel',
            name='market',
            field=models.CharField(default='', max_length=11),
        ),
    ]
