# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_rsimodel_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='', max_length=11)),
                ('base_volume', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('last', models.FloatField()),
                ('previous_day', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('change_12h', models.FloatField()),
                ('change_6h', models.FloatField()),
                ('rsi', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='marketgroupmodel',
            name='scanner_records',
            field=models.ManyToManyField(to='scanner.MarketModel'),
        ),
    ]
