# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20171124_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketgroupmodel',
            old_name='scanner_records',
            new_name='markets',
        ),
    ]
