# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_auto_20171124_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketgroupmodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 6, 43, 37, 198271)),
        ),
    ]
