# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_marketgroupmodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgroupmodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 6, 46, 53, 774519, tzinfo=utc)),
        ),
    ]
