# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_auto_20171127_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmodel',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
