# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_marketmodel_datetime_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(default='', max_length=2)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
