# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 23:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_auto_20171208_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
