# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_auto_20171208_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
